[package]
name = "brycki404/fluxa"
description = "Custom Runtime Animation Engine"
version = "4.1.2"
registry = "https://github.com/UpliftGames/wally-index"
authors = ["Brycki404"]
include = [
     "src"
]
exclude = [
     ".vscode",
     "rokit.toml",
     ".luaurc",
     "sourcemap.json",
     "selene.toml",
     "README.md",
     "docs",
     ".gitignore",
     "node_modules",
     "DevPackages",
     "dev",
     "dev.project.json",
]
realm = "shared"

[dependencies]

[server-dependencies]

[dev-dependencies]